# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run package
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-artifacts
          path: dist/fair*.exe
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run package
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macos-artifacts
          path: dist/fair*.dmg
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run package
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macos-artifacts
          path: dist/fair*.AppImage
